### PR TITLE
merge all my old stuff that I reverted

### PR DESCRIPTION
**Pull request by ampurr**
Learning a lot about how git does things! Some things you know intellectually, but then you realize you don't know how it applied in practice. Till now.

### CODE REVIEW

**Comment by ampurr** [comment]
@tdhock, requesting permission to merge changes from `animint2/main-delete-later-from-ampurr` into `animint2/reference-website-yay`. My goal is to copy the commits from the master branch so that GitHub stops telling me I'm 7 commits behind.

The `animint2/main-delete-later-from-ampurr` branch is just a copy of `animint2/master`. I made this branch cuz I was worried about messing up again and wanted to insulate `animint2/master` from another accident.

**Comment by tdhock** [comment]
the files changed tab says there are no changes, so can you please clarify what you want me to review here?
in general, you can do whatever you want to non-master branches, but please ask for review when attempting to merge commits into master.

**Comment by ampurr** [comment]
Oh! Well, there's nothing to review besides the accidental commits and the reversion. But I was under the impression that I had to get your approval for all merges. Your note on non-master branches helped clarify when I should ask for a review.

Since there's nothing to review and it doesn't involve `animint2/master`, I'll merge. Thanks. :>

**Comment by tdhock** [comment]
great

**Pull request merged**
