### PR TITLE
Add WorldBank test

### PR DESCRIPTION
**Pull request by nhintruong**
Adding WorldBank for the hard test in GSOC 2024 application

### CODE REVIEW

**Comment by tdhock** [comment]
great thanks for the contribution!
Can you please clarify if your new code tests any functionality which is not already covered in the other tests?

**Comment by nhintruong** [comment]
This is a [testthat unit test](https://github.com/tdhock/animint/wiki/Testing) based on one of my Animint visualizations, as requested in the hard test section [here](https://github.com/rstats-gsoc/gsoc2024/wiki/Animated-interactive-ggplots). I don't think there is any new functionality being tested. Please let me know if you would like me to do so.

**Comment by tdhock** [comment]
it would be good if you could check code coverage, and see if you could add a test that increases coverage.
this could be added to GSOC goals (computing coverage for R code on Github actions should be easy, would be nice if we could compute javascript coverage too)

**Comment by nhintruong** [comment]
Yes, I can do that. Should I add this to the test section in the proposal, or in one of the goals of the project?

**Comment by tdhock** [comment]
sure, you can add it to tests and goals
continue discussion about code coverage #122

**Pull request closed without merging**
